// flow-typed signature: 0f1908c3e38725fe8c272c8adcf9dd08
// flow-typed version: <<STUB>>/number-to-locale-string_v^1.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'number-to-locale-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'number-to-locale-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'number-to-locale-string/polyfill.number.toLocaleString' {
  declare module.exports: any;
}

declare module 'number-to-locale-string/polyfill.number.toLocaleString.spec' {
  declare module.exports: any;
}

declare module 'number-to-locale-string/test/jasmine-2.3.4/boot' {
  declare module.exports: any;
}

declare module 'number-to-locale-string/test/jasmine-2.3.4/console' {
  declare module.exports: any;
}

declare module 'number-to-locale-string/test/jasmine-2.3.4/jasmine-html' {
  declare module.exports: any;
}

declare module 'number-to-locale-string/test/jasmine-2.3.4/jasmine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'number-to-locale-string/polyfill.number.toLocaleString.js' {
  declare module.exports: $Exports<'number-to-locale-string/polyfill.number.toLocaleString'>;
}
declare module 'number-to-locale-string/polyfill.number.toLocaleString.spec.js' {
  declare module.exports: $Exports<'number-to-locale-string/polyfill.number.toLocaleString.spec'>;
}
declare module 'number-to-locale-string/test/jasmine-2.3.4/boot.js' {
  declare module.exports: $Exports<'number-to-locale-string/test/jasmine-2.3.4/boot'>;
}
declare module 'number-to-locale-string/test/jasmine-2.3.4/console.js' {
  declare module.exports: $Exports<'number-to-locale-string/test/jasmine-2.3.4/console'>;
}
declare module 'number-to-locale-string/test/jasmine-2.3.4/jasmine-html.js' {
  declare module.exports: $Exports<'number-to-locale-string/test/jasmine-2.3.4/jasmine-html'>;
}
declare module 'number-to-locale-string/test/jasmine-2.3.4/jasmine.js' {
  declare module.exports: $Exports<'number-to-locale-string/test/jasmine-2.3.4/jasmine'>;
}
