// flow-typed signature: f6e6d9cfbed2f28a906d383a68ebc2e5
// flow-typed version: <<STUB>>/react-native-pie_v^0.4.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-pie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-pie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-pie/src/Pie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-pie/src/Pie.js' {
  declare module.exports: $Exports<'react-native-pie/src/Pie'>;
}
